// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShoppingList.Data;

namespace ShoppingList.Migrations
{
    [DbContext(typeof(ShoppingListContext))]
    partial class ShoppingListContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ShoppingList.Models.ShopItemModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Section")
                        .HasColumnType("int");

                    b.Property<int>("Unit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ShopItemModel");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Shop item 1",
                            Quantity = 5,
                            Section = 1,
                            Unit = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Shop item 2",
                            Quantity = 2,
                            Section = 4,
                            Unit = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Shop item 3",
                            Quantity = 1,
                            Section = 5,
                            Unit = 2
                        },
                        new
                        {
                            Id = 4,
                            Name = "Shop item 4",
                            Quantity = 100,
                            Section = 2,
                            Unit = 3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
